[package]
name = "proxy-server"
description = "proxy-server."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/proxy-server"
documentation = "https://docs.rs/proxy-server"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[[bin]]
name = "serve-proxy"
path = "src/main.rs"

[dependencies]
